[book]
authors = ["André Willyan", "Said Rodrigues"]
language = "en"
multilingual = false
src = "src"
title = "Vondel Language and Microarchitecture"

[output.html]
git-repository-url = "https://github.com/thewillyan/vondel"
default-theme = "ayu"
